# Generated by Django 6.0.3 on 2026-03-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProConteo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='meta_diaria',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='meta_total',
            field=models.IntegerField(default=0),
        ),
    ]
