# Generated by Django 6.0.3 on 2026-03-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProConteo', '0002_proyecto_meta_diaria_proyecto_meta_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
